Docs: Agregar resumen del capitulo 9
IIKUYY/HTML5 pull request #10
Opened 2023-08-04 09:03 UTC by IIKUYY

## what

- Agregar el resumen del capitulo 9 junto con sus ejemplos

## why

- Continuar con las tareas dadas

## references
- http://diveintohtml5.info/index.html

2023-08-04 14:26 UTC, semanticmx commented on Ch9/Ejemplo/index.html
> +        name="viewport"
este formato está perfecto!

2023-08-04 14:27 UTC, semanticmx commented on Ch9/Ejemplo/index.html
> +    </h1>
aquí faltó identar el H1 para que esté en línea con la etiqueta de apertura.

2023-08-04 14:27 UTC, semanticmx commented on Ch9/Ejemplo/index.html
> +            <option
cuando solo hay 1 atributo ese si puede ir en la misma línea

2023-08-04 14:29 UTC, semanticmx commented on Ch9/Ejemplo/index.html
> +        <h3>
además de etiquetas de headings también como ejemplo puedes ocupar etiquetas label que tienen un atributo especial para los forms que es el `for`

por ejemplo:

```html
<label for=spinbox1>
  Spinbox
</label>
<input 
  id=spinbox1
  type=checkbox>
```

2023-08-04 14:31 UTC, semanticmx commented on Ch9/Ejemplo/index.html
> +        <input type="submit" value="submit">
este hay que ponerlo en una columna porque son dos atributos

2023-08-04 14:33 UTC, semanticmx requested changes
muy bien, son ajustes mínimos, ya que hay que actualizar el PR puedes agregar un segundo screenshot en un navegador diferente? 

Solo para mostrar que los elementos de los forms se ven de acuerdo a como cada navegador quiera mostrarlos.

2023-08-07 15:32 UTC, IIKUYY commented
Cambios realizados

2023-08-07 15:48 UTC, semanticmx approved these changes

2023-08-07 15:48 UTC, merged