Docs: Agregar resumen del capitulo 11
IIKUYY/HTML5 pull request #12
Opened 2023-08-09 13:45 UTC by IIKUYY

## what

- Agregar el resumen del capitulo 11 junto con sus ejemplos

## why

- Continuar con las tareas dadas

## references
- http://diveintohtml5.info/index.html

2023-08-09 19:42 UTC, semanticmx requested changes

2023-08-09 19:42 UTC, semanticmx commented on Ch11/Ejemplo/index.html
> +    <header
Aquí el formato va así:

```html
<header id="title">
    Ejemplo del uso del API de historial
</header>
```

porque header solo tiene un atributo

2023-08-09 19:42 UTC, semanticmx commented on Ch11/Ejemplo/index.html
> +    <script
muy bien

2023-08-09 19:42 UTC, semanticmx commented on Ch11/Ch11.md
> +## Introducción
solo falta agregar los screenshots del navegador y listo.

2023-08-10 01:47 UTC, IIKUYY commented
Se realizaron los cambios

2023-08-10 01:50 UTC, semanticmx approved these changes

2023-08-10 01:50 UTC, merged