Features chapter2
IIKUYY/HTML5 pull request #3
Opened 2023-06-29 04:16 UTC by IIKUYY

## what

- Agregar resumen del capitulo 2 junto con ejemplos de uso

## why

- Continuar con las tareas dadas

## references
- http://diveintohtml5.info/index.html

2023-06-29 04:17 UTC, IIKUYY commented
Para hacer los ejemplos use una mezcla de búsquedas de google, IA y mis conocimientos, esto debido a que aun no manejo del todo bien JavaScript, si encuentra algo que se pueda optimizar o este mal hecho por favor hágamelo saber

2023-07-06 21:12 UTC, semanticmx requested changes

2023-07-06 21:12 UTC, semanticmx commented on Ch2/Ch2.md
> +<head>
como en este curso usamos un poco más de código voy a ir agregando correcciones para que las apliques en el PR actual y en los siguientes, estas correcciones van formando nuestra guía de estilo conforme las vamos haciendo.

https://github.com/semanticmx/html5-coding-standards

La puedes ir revisando y aplicando conforme avances con el curso

El primer cambio que necesitamos aquí es identar los elementos dentro del tag html.

actual
```
<html>
<head>
...
</body>
<
```

deseado
```
<html>
  <head>
  ...
  </body>
<
```

2023-07-06 21:12 UTC, semanticmx commented on Ch2/Metodos/Metodo1/M1.html
> +    <head>
acá la identación quedo perfecto, los IDEs te ayudan con eso.

2023-07-06 21:12 UTC, semanticmx commented on Ch2/Metodos/Metodo1/M1.js
> +function supports_geolocation() {
Si tu usas la tecla de TAB en el teclado para identar, los espacios siempre van a ser los mismos y si configuras el IDE para que siempre te convierta los TAB's a 2 o 4 espacios entonces no habrá problemas de que las líneas de código queden identadas a diferentes espacios.

2023-07-06 21:12 UTC, semanticmx commented on Ch2/Metodos/Metodo2/M2.js
> +function supports_canvas_text() {
para los métodos en JavaScript vamos a usar camelCase

en lugar de supportsCanvasText

que diga: supportsCanvasText

2023-07-06 21:12 UTC, semanticmx commented on Ch2/Metodos/Metodo2/M2.js
> +    var dummy_canvas = document.createElement('canvas');
lo mismo para nombres de variables

2023-07-06 22:30 UTC, semanticmx approved these changes

2023-07-06 22:30 UTC, merged