Features chapter5
IIKUYY/HTML5 pull request #6
Opened 2023-07-19 07:54 UTC by IIKUYY

## what

- Agregar el resumen del capitulo 4 junto con sus ejemplos
- Agregar vínculos a los menús

## why

- Continuar con las tareas dadas
- Mantener el uso correcto de TOC de navegación

## references
- http://diveintohtml5.info/index.html

2023-07-19 16:48 UTC, semanticmx requested changes
también puedes agregar screenshots de algún video

2023-07-19 16:48 UTC, semanticmx commented on Ch5/Ejemplo/index.html
> +                <source src="pr6.webm" type="video/webm; codecs=vp8,vorbis"/>
los atributos de esta etiqueta también deben ir en 1 sola columna.

2023-07-19 16:48 UTC, semanticmx commented on Ch5/Ejemplo/index.html
> +                <object width="320" height="240" type="application/x-shockwave-flash" data="http://releases.flowplayer.org/swf/flowplayer-3.2.1.swf">
igual acá, una sola columna

2023-07-19 16:48 UTC, semanticmx commented on Ch5/Ejemplo/index.html
> +                        Download video as <a href="i/pr6.mp4">MP4</a>
la etiqueta <a> va en una línea a parte.

2023-07-19 20:39 UTC, IIKUYY commented
Cambios realizados conforme a lo requerido

2023-07-21 06:20 UTC, semanticmx approved these changes
muy bien!

2023-07-21 06:20 UTC, merged