Docs: Agregar resumen del capitulo 6
IIKUYY/HTML5 pull request #7
Opened 2023-07-26 00:20 UTC by IIKUYY

## what

- Agregar el resumen del capitulo 6 junto con sus ejemplos

## why

- Continuar con las tareas dadas

## references
- http://diveintohtml5.info/index.html

2023-07-26 15:44 UTC, semanticmx commented on Ch6/Ch6.md
> +## Geoposition,js
creo que esta es una coma y debe ser un punto.

2023-07-26 15:52 UTC, semanticmx requested changes
muy bien!

2023-07-26 15:52 UTC, semanticmx commented on Ch6/Ejemplo/index.html
> +        <script src="geoPosition.js"></script>
en el ejemplo de arriba el script lo colocaste como parte del body.

Hay ventajas y desventajas en colocarlo en el body o en el head.

Si se coloca en el `<head>` dado que HTML es un lenguaje interpretado la carga del sitio se bloqueará por unos instantes y en ese tiempo verás una página en blanco, hasta que termine la ejecución del script. Esto no es deseable y se puntua bajo en los scripts que analizan el performance de las páginas.

https://www.modpagespeed.com/doc/filter-js-defer

Como se menciona en el link de arriba, lo recomendable es esperar a que todo el HTML se haya cargado para hasta ese momento cargar scripts, esto se logra de varias formas, la más fácil siendo agregar la etiqueta <script> justo antes de la etiqueta de cierre </body>

Solo que antes de usar la librería debemos esperar a que haya sucedido el evento onload, que se ejecuta una vez que todo el HTML de la página ha sido cargado.

Para este ejemplo dado que dentro de main.js solo hay funciones que se ejecutan al dar click en un botón es seguro mover estos dos scripts al final de la página.

Como lo estas corriendo de forma local tal vez no notes la diferencia pero por eso existen herramientas que detectan este tipo de ajustes y calculan el impacto en el tiempo de carga de las páginas.

2023-07-27 23:36 UTC, IIKUYY commented
Se realizaron los cambios necesarios

2023-07-28 17:00 UTC, semanticmx approved these changes
perfecto!

2023-07-28 17:01 UTC, merged