Features chapter 7
IIKUYY/HTML5 pull request #8
Opened 2023-07-29 03:29 UTC by IIKUYY

## what

- Agregar el resumen del capitulo 7 junto con sus ejemplos

## why

- Continuar con las tareas dadas

## references
- http://diveintohtml5.info/index.html

2023-07-31 16:39 UTC, semanticmx requested changes
muy bien, igual trata de agregar los screenshot al README.md con la implementación del html/JS/CSS que vayas haciendo en los capítulos

2023-07-31 16:39 UTC, semanticmx commented on Ch7/Ejemplo/index.html
> +  <script src="main.js"></script>
esta perfecto solo que todos los tags deben ir dentro del body.

en lugar de:

```html
</body>
   <script src="main.js"></script>
```

debe ser

```html
    <script src="main.js"></script>
</body>
```

2023-07-31 16:39 UTC, semanticmx commented on Ch7/Ejemplo/main.js
> +var counterVal = parseInt(localStorage.getItem('counterValue')) || 0;
por convensión vamos a listar primero las funciones y después ya las acciones por ejemplo, la definición de las funciones iría hasta arriba y ya la parte de la creación de counterVal y la llamada a updateDisplay quedaría hasta abajo.

2023-07-31 22:15 UTC, IIKUYY commented
Cambios del código realizados, ¿las screenshots las pide en README.md general o en de cada capitulo?

2023-07-31 22:18 UTC, semanticmx commented
> Cambios del código realizados, ¿las screenshots las pide en README.md general o en de cada capitulo?

Yo diría que quedan bien en cada capítulo.

2023-07-31 22:19 UTC, IIKUYY commented
Vale, entonces las subo en este commit

2023-07-31 22:38 UTC, IIKUYY commented
Imágenes agregadas

2023-08-01 02:51 UTC, semanticmx approved these changes

2023-08-01 02:51 UTC, merged