Docs: Agregar resumen del capitulo 8
IIKUYY/HTML5 pull request #9
Opened 2023-08-02 08:29 UTC by IIKUYY

## what

- Agregar el resumen del capitulo 8 junto con sus ejemplos

## why

- Continuar con las tareas dadas

## references
- http://diveintohtml5.info/index.html

2023-08-02 15:11 UTC, semanticmx requested changes
muy bien, solo hay que reemplazar los screenshots y colocar los del browser

2023-08-02 15:11 UTC, semanticmx commented on Ch8/Assets/HTML5.png
Para los screenshots pueden ser solo del navegador para ver el resultado del html, ya que el código lo tenemos en git.

2023-08-03 05:14 UTC, IIKUYY commented
Cambios realizados

2023-08-03 19:13 UTC, semanticmx approved these changes
muy bien!

2023-08-03 19:13 UTC, merged